<?php
    $_helper = $this->helper('catalog/output');
    $_product = $this->getProduct()
?>
<?php if($_additional = $this->getAdditionalData()): ?>
<?php foreach ($_additional as $_data): ?>
<table class="data-table" id="product-attribute-specs-table">
    <col width="25%" />
    <col />
    <thead>
        <tr>
            <th colspan="2"><?php echo $_data['title'] ?></th>
        </tr>
    </thead>
    <tbody>
        <?php foreach($_data['attributes'] as $attribute): ?>
        <tr>
            <th class="label"><?php echo $this->escapeHtml($this->__($attribute['label'])) ?></th>
            <td class="data"><?php echo $_helper->productAttribute($_product, $attribute['value'], $attribute['code']) ?></td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>
<?php endforeach; ?>
<script type="text/javascript">decorateTable('product-attribute-specs-table')</script>
<?php endif;?>